### ISSUE TITLE
Update documentation?

### ISSUE THREAD

**Issue by JetSetDoritos** [octohub/GroupMeAnalytics#10]
The readme says 

> Grab python 2.7.x (this app is not compatible with python 3.4.x)

I notice 3 support was added in https://github.com/octohub/GroupMeAnalytics/commit/3372f1a9083e53587a5df4debea277f327b2bf24

I just lost a good chunk of time hitting errors trying to run it in 2.7, I should of noticed it was written in 3 though honestly, but updating that line of the readme should help others not be a dummy like me :P

Edit: Sorry I just noticed this is sorta a duplicate of #7

**Comment by ErikBoesen** [comment]
This is much more specific than #7. I will make a pull request to fix this.

**Comment by ErikBoesen** [comment]
Fixed.
