### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by ErikBoesen** [octohub/GroupMeAnalytics#11]
@octohub  Can I have this repository transferred to my acount/be given administrator access so I can update the repo tagline?

**Comment by octohub** [comment]
@ErikBoesen What would you like me to update it to? Thanks for the help brother.

**Comment by ErikBoesen** [comment]
"A simple Python app that gives insight into your GroupMe conversations."

**Comment by octohub** [comment]
Done. You are a man of detail, you'll go far.
