### ISSUE TITLE
Only Returning Half of Group Members

### ISSUE THREAD

**Issue by flyblackbox** [octohub/GroupMeAnalytics#3]
After I run the script, only analytics are provided for 3/6 of the users in my group.
There is no error, please help!

**Comment by flyblackbox** [comment]
:'(

**Comment by ErikBoesen** [comment]
I am unable to reproduce this issue. Please feel free to reopen if you can provide more specific information.

**Comment by openequity** [comment]
Let me try it again as it was a long time since I tried it.
